### ISSUE TITLE
Could not find style module 'algforopt'

### ISSUE THREAD

**Issue by AshtonSBradley** [sisl/tufte_algorithms_book#34]
On a fresh clone in MacOS Ventura, with julia 1.8.0: 

`make test` gives: ALL TESTS PASSED.

But `make compile` gives

```
This is PythonTeX 0.18
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/texlive/20220321_3/libexec/lib/python3.10/site-packages/pygments/styles/__init__.py", line 82, in get_style_by_name
    mod = __import__('pygments.styles.' + mod, None, None, [cls])
ModuleNotFoundError: No module named 'pygments.styles.algforopt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/texlive/20220321_3/share/texmf-dist/scripts/pythontex/pythontex3.py", line 2403, in do_pygments
    formatter[codetype] = LatexFormatter(**p)
  File "/usr/local/Cellar/texlive/20220321_3/libexec/lib/python3.10/site-packages/pygments/formatters/latex.py", line 257, in __init__
    Formatter.__init__(self, **options)
  File "/usr/local/Cellar/texlive/20220321_3/libexec/lib/python3.10/site-packages/pygments/formatter.py", line 66, in __init__
    self.style = _lookup_style(options.get('style', 'default'))
  File "/usr/local/Cellar/texlive/20220321_3/libexec/lib/python3.10/site-packages/pygments/formatter.py", line 21, in _lookup_style
    return get_style_by_name(style)
  File "/usr/local/Cellar/texlive/20220321_3/libexec/lib/python3.10/site-packages/pygments/styles/__init__.py", line 84, in get_style_by_name
    raise ClassNotFound("Could not find style module %r" % mod +
pygments.util.ClassNotFound: Could not find style module 'algforopt'.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/texlive/20220321_3/share/texmf-dist/scripts/pythontex/pythontex3.py", line 2882, in <module>
    main(python=sys.version_info.major)
  File "/usr/local/Cellar/texlive/20220321_3/share/texmf-dist/scripts/pythontex/pythontex3.py", line 2828, in main
    do_multiprocessing(data, temp_data, old_data, engine_dict)
  File "/usr/local/Cellar/texlive/20220321_3/share/texmf-dist/scripts/pythontex/pythontex3.py", line 1390, in do_multiprocessing
    result = task.get()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
pygments.util.ClassNotFound: Could not find style module 'algforopt'.
make: [compile] Error 1 (ignored)
```

**Comment by mykelk** [comment]
I think you need this: https://github.com/sisl/pygments-style-algforopt
